src/jsd.c

If jsd fails to connect to an ethercat device, it suggests that the connection failed because it was not run as `root`
```c
ERROR("No socket connection on %s. Excecute as root", ifname);
```
However there are other reasons why the socket connection may have failed, such as the device not being switched on or improperly configured. On a failed connection, jsd complains about needing root even when the script is being run as root/sudo. 
This update detects if the user is running as root and emits a more helpful error message.

Detect if user is running as root when reporting failed socket connection

---

src/jsd_egd.c
src/jsd_egd_types.h

The `0x6080` data object `max motor speed` accepts units of RPM instead of the expected cnts/sec. This conversion to RPM is now being done internally so as to keep the JSD API speeds in cnts/sec.

max speed fix

---

CMakeLists.txt

Replace SOEM remote URL with https so no SSH token needed in downstream projects (e.g. CI)

Replaced ssh with https soem remote to remove need for ssh token

---

src/CMakeLists.txt
src/jsd.c
src/jsd_el3162.c
src/jsd_el3162.h
src/jsd_el3162_pub.h
src/jsd_el3162_types.h
src/jsd_types.h
test/CMakeLists.txt
test/device/jsd_el3162_test.c

Summary:
Adds the JSD driver for the Beckhoff EL3162 terminal which is a
2-channel analog input for voltage range 0-10 V. Inputs have
reference ground as common ground potential.
Test Plan:
Performed preliminary testing via the written test executable and
the terminal connected to a local EtherCAT network. No inputs were
connected yet.
Reviewers: alex-brinkman, JosephBowkett

Adds driver for Beckhoff EL3162 analog input

---

src/jsd_egd.c

* In EGD, set the PL[1] on initialization. This value is also set on every PDO exchange (and I tested that works) but the EAS Two-Letter Command interface did not reflect this value, hopefully this helps head off potential issues.
* Added display for UM[1] on initialization.  
* Added handler for async SDO on UM[1] mode change

Abrinkma set pl1 on init

---

src/jsd_egd.c
src/jsd_egd_pub.h
src/jsd_egd_types.h
src/jsd_sdo.c
src/jsd_types.h

Summary:
Extends the Elmo Gold Drive's driver to enable the selection of the
gain scheduling strategy for its controller and the selection of
particular gain sets when the strategy is manual scheduling.
Test Plan:
Tested by temporarily modifying test/device/jsd_egd_csp_sine_test.c
to periodically switch between two sets of gains. The switch of
gains was corroborated by watching the behavior of the motor shaft
while tracking position.
Reviewers: alex-brinkman, JosephBowkett

Adds gain scheduling capabilities to EGD's driver.

---

src/jsd_egd.c
src/jsd_egd_types.h
test/device/jsd_egd_csp_sine_test.c
test/device/jsd_egd_test.c

Summary:
Fixes issue with EGD's gain scheduling mode configuration when the drive's pre-loaded mode is desired. The root of the problem was a type cast issue between an enumeration type and an integer type.
Test Plan:
Tested with fcat and an actual motor. The fcat ROS1 module was modified for this test to support the EGD Fastcat driver.
Reviewers: JosephBowkett, alex-brinkman

Fixes EGD's gain scheduling config when absent

---

src/jsd_include_defs.h

EELS 27 actuator FastCAT bus ran out of IO map space, and they'll be going as high as 40 actuators.
Smallest multiple of 2 that will cover 40 is 4096, tested working on the 27 actuator robot.

Quadrupled IO map size for EELS

---

src/jsd_print.h
src/jsd_time.h

Adds the system time to the jsd_print.h log messages.

Add timestamp to jsd_print.h macros.

---

src/jsd_time.h

the `#ifdef` statement used the file name `JSD_TIME_H_` while the `#define` statement used `JSD_TIME_H` which caused a error while building the project

fix incorrect header guard

---

src/jsd_egd.c

Summary:
The fault_code variable in the EGD's state was incorrectly assigned the raw Elmo error code instead of the corresponding enumeration value. This has been fixed.
Fixes #32
Reviewers: alex-brinkman, JosephBowkett

Fixes fault code assignment in EGD driver

---

src/jsd_sdo.c

the format specifiers for the `int64_t` and `uint64_t` types in the `printf` call were causing a compilation error.

fix format specifiers

---

src/jsd.c
src/jsd.h
src/jsd_egd.c

Removes `jsd_get_time_sec` and all references that clock.

removed jsd_get_time_sec for jsd_time_get_time_sec

---

src/jsd_egd.c
src/jsd_egd_types.h
src/jsd_time.h

Summary:
Adds function to get a time reference from the monotonic clock so that elapsed time can be computed.
Test Plan:
Ran jsd_egd_test on the Playground testbed and forced some velocity tracking errors. Behavior was equivalent to before the change.
Reviewers: alex-brinkman

Adds function to compute monotonic time.

---

src/jsd_egd.c

By default, we set quick-stop function(0x605A) with value 2: `Slow down on quick-stop ramp and then disable the drive function, go to SWITCHED ON DISABLED state`.
When motor finishes the profile, Elmo state machine state jumps to `Quick Stop Active`
If we command ELMO faster than 200hz, before the quick-stop function does the job to transit to `SWITCHED ON DISABLED` to brake the actuator, it jumps to `OPERATION_ENABLED` instead.
And when Elmo SMS is in `OPERATION_ENABLED` state, it was looping to set the controlword to stay in `OPERATION_ENABLED`, which will cause any automatic state transition not functional.
After removing those state transition, actuator was tested with 512 and 1024hz and braked properly after profile.

Removed unnecessary sms transition

---

src/jsd_egd.c
src/jsd_epd.c
src/jsd_epd_types.h

Added PDO channel size limit check to initialization of Gold and Platinum motor controller drivers.

PDO size check for EGD and EPD

---

src/jsd.c
src/jsd_epd.c
src/jsd_pub.h
test/CMakeLists.txt
test/device/jsd_epd_network_test.c
test/unit/jsd_soem_init_close_test.c

Updates JSD's initialization and write functions to use overlapping IOmap instead of the legacy IOmap. This supports both existing drivers and the new Platinum driver, making it possible to have Platinum drives in the same network as other devices.
The update in JSD's initialization also comprises calling ecx_writestate only once, as opposed to each cycle, while waiting to transition into Operational state. This is done because calling it multiple times can alter the behavior of some slaves.
Test Plan:
Tested on local network composed of an EL3602, and EL2124 and an Elmo Platinum motor controller.
Also tested on Playground with an Elmo Gold motor controller.

Fixes network communication issues with Platinum

---

src/jsd_egd.c

It was discovered that digital_output_index did not correspond to the indices expected for the ELMO digital output pins (OUT1 through OUT4) as well as the indices associated with the object (OB[1-4]). To fix this, one less bit shift is required.
Tested the new indexing on the testbed and confirmed this new shifting coincides with the expected index'ing pattern.

fix: resolve off-by-one issue

---

src/jsd_egd.c
src/jsd_epd.c

Asserts needed to be modified to ensure we can use the 4th digital output. Additional changes were made in the platinum drive code to match that on the gold drive.

fix: output index issue

---

src/jsd_epd.c
src/jsd_epd_pub.h

Adds a function in the EPD driver to clear latched errors in the driver's state. This function is needed in Fastcat to reset the drive from a Faulted state at the Fastcat level. Otherwise, Fastcat's state machine circles between Halted and Faulted because the transition into Halted requires the latched errors in the underlying JSD driver's state to be cleared.
Test Plan:
Tested on a Platinum connected with a motor through ros1/Fcat by inducing a velocity tracking error during a position command, resetting the actuator, and sending the command again. The second command was successfully followed.

Adds a function in EPD driver to clear latched errors in driver's state

---

src/jsd_epd.c
src/jsd_epd_types.h

EPD driver requested an Enable Operation's state machine transition inadvertently during Quick Stop Active.
The firmware in Platinum drives should ignore such request if Quick Stop Option Code is set to 2. However, some drives do not follow the documented behavior and transition into Enabled Operation from Quick Stop Active. As a consequence of this, if there is a brake configured in the drive, the brake will remain engaged after the Quick Stop.
Test Plan:
Tested on Safety and non-Safety Platinum drives connected to motors. The test consisted on sending one profiled position command, and sending a second one after completion of the first. Now the state machine does not transition to Enabled Operation from Quick Stop Active, and the motor's brake is engaged and disengaged properly.

Fixes Quick Stop transition in EPD driver

---

README.md
src/CMakeLists.txt
src/jsd.c
src/jsd_el1008.c
src/jsd_el1008.h
src/jsd_el1008_pub.h
src/jsd_el1008_types.h
src/jsd_types.h
test/CMakeLists.txt
test/device/jsd_el1008_test.c

This PR contains all the code necessary for the EL1008 driver. This is a common 8-channel digital input beckhoff module. This code has been tested using the Fastcat/FCAT stack. The unit test was also used to show proper state changes of the digital input.

Feat el1008 driver

---

CMakeLists.txt
src/jsd_ati_fts.c
src/jsd_egd.c

Suppress more unused variable warnings when setting log level to FATAL or WARNING. Thanks to Dennis Wai for the contribution.

Dwai jsd compile time verbosity level

---

src/jsd_egd.c
src/jsd_epd.c

It was found that if a fault occurs slightly after commands are sent from fastcat, it is possible that a halt could be sent before the JSD level has time to transition to its operational state.
Error scenario: 
Motion commands are sent and then a fault immediately occurs resulting in the immediate sending of the halt command. 
We see in this graph that the actuator transitions from "1" (HALTED) to "9" (ACTUATOR_SMS_CS) to "0" (FAULT). Within the same cycle, the JSD level transitions from "35" (JSD_ELMO_STATE_MACHINE_STATE_SWITCHED_ON) to "39" (JSD_ELMO_STATE_MACHINE_STATE_OPERATION_ENABLED). It then proceeds to stay enabled perpetually running at the command set when the actuator state was in ACTUATOR_SMS_CS.
Why this occurs:
If the halt command is processed before JSD has a chance to …

fix: initial commit

---

src/jsd_egd.c
src/jsd_egd_types.h
src/jsd_epd.c
src/jsd_epd_types.h

This pull request is a follow up of the previous pull request for fix-persistent-halt-command.
This pull request solves the problem using a flag that ensures that the ELMO has time to switch to operation enabled before processing halt commands.
Thus far, this implementation is untested.

Fix persistent halt command

---

src/jsd_error_cirq.c
src/jsd_sdo.c

Needed to decrease the length by 1 to account for warnings that result in errors for exacting builds.

feat: initial commit

---

src/jsd.c
src/jsd.h
src/jsd_pub.h
test/device/jsd_minimal_example_el3602.c
test/jsd_test_utils.c
test/unit/jsd_soem_init_close_test.c
tools/jsd_egd_tlc_tty.c

This pull request adds jsd inspect context. This function gets EC state information from each state in the scenario that a state does not reach operational mode during the initialization.
In this function, we report the states of each slave and information from the ethercat elist.

jsd inspect context

---

src/jsd.c
src/jsd_pub.h
test/device/jsd_minimal_example_el3602.c
test/jsd_test_utils.c
test/unit/jsd_soem_init_close_test.c
tools/jsd_egd_tlc_tty.c

It was found that some devices, specifically Platinum drives, would not transition into operational state. From debugging, research, and headaches, it was found that the issue was due to non-timely sending of PDOs. When PDOs are not sent at a timely rate, the slave will not transition to Operational mode.
This information is presented here:
https://github.com/OpenEtherCATsociety/SOEM/issues/224
"Mostly a 1ms cycle time will work. When the slave sees enough LRW packets at a constant interval it will lock to that and release to Operational."

Added a short delay to ensure timely PDOs
